SELECT TOP (1000) [CURP]
      ,[ApellidoPaterno]
      ,[ApellidoMaterno]
      ,[Nombres]
      ,[Sexo]
      ,[FechaNacimiento]
      ,[Direccion]
      ,[Tipo]
  FROM [CONQUISTADORES].[dbo].[Personaa]